In [3]:
import numpy as np

In [9]:
cc = np.eye(2)

In [10]:
cc

array([[1., 0.],
       [0., 1.]])

In [4]:
aa = np.array([[1, 2, 3]])

In [8]:
aa.T

array([[1],
       [2],
       [3]])

In [5]:
aa.ndim

2

In [6]:
aa.shape

(1, 3)

In [3]:
bb = np.array([1., 2., 3.])

In [4]:
bb.dtype

dtype('float64')

In [5]:
arr = np.arange(0, 4*2*4)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr.ndim

1

In [9]:
arr.shape

(32,)

In [10]:
arr.strides

(4,)

In [11]:
rarr = arr.reshape([4,2,4])

In [12]:
rarr.ndim

3

In [15]:
rarr.shape

(4, 2, 4)

In [16]:
rarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [17]:
x_rarr = rarr.sum(axis=0)

In [18]:
x_rarr.ndim

2

In [19]:
x_rarr.shape

(2, 4)

In [20]:
x_rarr

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [21]:
y_rarr = rarr.sum(axis=1)

In [22]:
y_rarr.ndim

2

In [23]:
y_rarr.shape

(4, 4)

In [24]:
y_rarr

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])